### ISSUE TITLE
Unable to launch the mod on windows 10 on ARM

### ISSUE THREAD

**Issue by alskdh** [krypto5863/COM-Modular-Installer#2]
Is it able to install the module on windows 10 on ARM? I have downloaded the file and try to install however it is unable to launch it. I am using the m1 mac with parallels now

**Comment by krypto5863** [comment]
Never thought someone would try it on ARM, wow. While Inno does have support for ARM, it's possible that my external net framework helper plugin won't work too well on ARM. If there's some way you can look into net framework compatibility on your system, I'd advise that for now.

**Comment by krypto5863** [comment]
Due to no further response, I will be closing this issue.
