### ISSUE TITLE
Receiving out of date error on initial start installation process

### ISSUE THREAD

**Issue by moko02** [krypto5863/COM-Modular-Installer#21]
When trying to install CMI - I receive an error saying out of date.  I did update to the latest 2.26 from site and the current version I have is the R18 + GP-01 from S-Court.  The game works fine and installation process of the game seems fine not sure what to do here.

![image](https://github.com/krypto5863/COM-Modular-Installer/assets/92999767/f83aee8c-5e7f-44c1-9e9a-0ecc1826bf8f)

**Comment by krypto5863** [comment]
CMI is never wrong. If it says you improperly updated, then you likely did. Avoid putting anything in your game directory next time.
