### ISSUE TITLE
Installer does not support mapped network drive with SMB

### ISSUE THREAD

**Issue by MakiseKurisu** [krypto5863/COM-Modular-Installer#22]
The installer is launched as Admin, but IIRC in Windows mapped drive is only accessible from user account. I used to encounter this issue with the LOB application I maintained for my former employer.

**Comment by krypto5863** [comment]
That's unfortunate but that setup is a little complicated to work with. I can let CMI run as a normal user but it might cause installation issues for other users. I'll ponder on that for now...
