### ISSUE TITLE
You can add VYM .

### ISSUE THREAD

**Issue by PantaFH** [krypto5863/COM-Modular-Installer#24]
Hello, after some observation, you can now add VYM back. After communication with the author, the previous bugs and problems have been resolved, and the author has been updating new features. You can find its latest version [here](https://x.com/ankokusamochi).

**Comment by krypto5863** [comment]
That's really good to hear, but I removed VYM because it wasn't consistent anymore with the idea behind CMI which was to enhance the main game and gameplay. VYM seems to be more of it's own side activity.

**Comment by PantaFH** [comment]
Thank you for your reply, but some players have mentioned this' remote control 'plugin on the forum. But I support your viewpoint and hope to have more communication with you. Thank you!

**Comment by PantaFH** [comment]
Thank you for your reply, but some players have mentioned this' remote control 'plugin on the forum. But I support your viewpoint and hope to have more communication with you in the future. Thank you!
