### ISSUE TITLE
Won't  let me update to version 1551

### ISSUE THREAD

**Issue by RaptorTim** [krypto5863/COM-Modular-Installer#3]
It tells me that my game is outdated, so I went to install it my self, but it's the same version I already have. Even when I press "no" after asking to auto-update, it still brings me to the same one. I'm using Steam version R18 patch installed. Version 108.1 and that's the only update available

**Comment by krypto5863** [comment]
Not a bug. 1.08.1 is the english equivalent of 1.54 JP. CMI 2.4.8.1 required 1.55.1 (english has no equivalent). I've released 2.4.8.2 that resolves this issue.
