### ISSUE TITLE
Error parsing version

### ISSUE THREAD

**Issue by andrejcremoznik** [krypto5863/COM-Modular-Installer#4]
I'm getting

```
An error occurred while parsing the version number... Report this to the dev.
```

Looking at the code there seems to be some remote fetching going on https://github.com/krypto5863/COM-Modular-Installer/blob/db41e69f555470a24c679e96640e86ba058336c7/VersionVerification.iss#L136

I'm getting a 404 on those URLs. I didn't look any further because I'm not familiar with the code or language.

The `update.lst` file I have is from the `com3d2_up155.1.zip` official JP update

**Comment by krypto5863** [comment]
The remotes fetches aren't related, it's more than likely having an issue parsing the version from your update.lst. Could be a variety of issues that can cause this but we can start with your update.lst file in particular.

Could you upload your update.lst file somewhere and send it? I should be able to see what's going on with that.

**Comment by andrejcremoznik** [comment]
Here https://privatebin.net/?65171d3eef8b12c2#ExbxUHycmxY7RSqg7khYwqCqJLFfom8TXmJ3YxxMxK2U

It's the same file as in the 155.1 update from http://com3d2.jp/oldupdate/ .

**Comment by krypto5863** [comment]
The update.lst files in the updates or dlcs aren't the same as the ones in your game folder. So unless you are using the update.lst from an update or dlc (you really shouldn't do this) then send the one inside your game folder.

If you are by chance drag and dropping dlc or mods into your game folder and/or this really is your update.lst from your game folder, then your game is broken. Use the update.exe instead after you reinstall your game.

**Comment by andrejcremoznik** [comment]
> If you are by chance drag and dropping dlc or mods into your game folder

Oops. Let me correct that and see if it works.

**Comment by krypto5863** [comment]
Meant to say DLC and Updates. Mods are drag and dropped to an extent.

**Comment by andrejcremoznik** [comment]
It was my mistake not paying attention and copying files over. It works now, thanks!
