### ISSUE TITLE
please  change in COM3D2\scripts\*.cs files

### ISSUE THREAD

**Issue by lilly1987** [krypto5863/COM-Modular-Installer#5]
https://github.com/BepInEx/HarmonyX/wiki/Patching-with-Harmony#unpatching-all-methods-of-an-instance

please  change in COM3D2\scripts\*.cs files
```c#
    public static void Unload() {
        //instance.UnpatchAll();//before
        instance.UnpatchSelf();//after 1
        //instance.UnpatchAll(instance.Id); //or after 2
        instance = null;
    }
```

**Comment by krypto5863** [comment]
I'll see about doing this soon. Some scripts don't like this very much as the ScriptLoader needs a recompilation to include the new `UnpatchSelf()` method. `instance.UnpatchAll(instance.Id)` has the exact same effect though.
