### ISSUE TITLE
Yotogi and Shape Animator Plugin are in Japanese

### ISSUE THREAD

**Issue by Codesterz** [krypto5863/COM-Modular-Installer#7]
I'm on the English version of the game and used COM modular installer 2.5.0.1, but both Shape Animator Dance Plus and Yotogi Plugin are in Japanese. Is there a way to fix this? When I installed CMI there was a part where it asked me if I wanted to disable translations and I said yes because I didn't want google translations for everything(mainly character dialogue and story). Did this also disable translation for those plugins?

**Comment by Codesterz** [comment]
Looks to be another bug going on as well. Clicking the + button in shape animator causes this message to show up. 

[Error  : Unity Log] TypeLoadException: Could not load type 'Slot'.
Stack trace:
CM3D2.ShapeAnimator.ShapeAnimator.GuiFunc (Int32 winId)
UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)

**Comment by krypto5863** [comment]
This was resolved in the discord channel but I'll re-explain the solution for posterity.

2.5.0.1 has an issue where both CR and Non-CR versions of ShapeAnimator are installed. This can be easily corrected by removing the offending version. This information was noted in the Known Issues section of the 2.5.0.1 release.

As for translations, YotogiUtil has partial translations but it should be operating correctly. ShapeAnimator has full translations but requires the version within CMI.
