### ISSUE TITLE
Is 'kiss your maid' plugin obsolete?

### ISSUE THREAD

**Issue by JohnCenaHacker** [krypto5863/COM-Modular-Installer#8]
I just realize 'kiss your maid' plugin doesn't exist anymore in CMI, why? :'
Here's the link of plugin, haven't tried it yet: https://ux.getuploader.com/com3d2_mod_kyouyu/download/50
.
I've tried it, it's safe
Installation: 
1. take COM3D2.KissYourMaid.Plugin.dll from the zip
2. put the COM3D2.KissYourMaid.Plugin.dll to COM3D2Folder/Sybaris/UnityInjector

Haven't try with VR yet, should be works fine :D

**Comment by krypto5863** [comment]
We removed a bunch of seemingly minor plugins (and honestly left a few more) and KissYourMaid was pretty specific purpose. There's currently no plans to re-add them.
